version: '2.1'
services:

    postgres:
        image: postgres:11
        networks:
            - production
        ports:
            - ${PG1_PORT}:5432
        environment:
            POSTGRES_USER: ${PG1_USER}
            POSTGRES_PASSWORD: ${PG1_PASSWORD}
            POSTGRES_DB: ${PG1_DB}
        volumes:
            - ${HUMBLE_DATA}/pg:/var/lib/postgresql/data
            - ${HUMBLE_BACKUP}:/backup
        restart: always

networks:
    production:
